[package]
name = "volume-level-ui"
version = "0.1.0"
authors = ["KrutNA <krutna@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex            = "1.3.9"
libpulse-binding = "2.16.0"
iced             = { path = "../../../../.other/iced/" }
iced_native      = { path = "../../../../.other/iced/native/" }
iced_wgpu        = { path = "../../../../.other/iced/wgpu/" }
iced_graphics    = { path = "../../../../.other/iced/graphics/" }
iced_style       = { path = "../../../../.other/iced/style/" }